### ISSUE TITLE
bench / feature set differences with https://git.sr.ht/~jackmordaunt/go-libwebp ?

### ISSUE THREAD

**Issue by gedw99** [HugoSmits86/nativewebp#2]
Hey @HugoSmits86 

https://github.com/HugoSmits86/nativewebp is better i think than https://git.sr.ht/~jackmordaunt/go-libwebp ?

Both avoid cgo .

Bench and check feature sets.

**Comment by HugoSmits86** [comment]
Great question! nativewebp is fully Go-native, simple, and focused on lossless WebP (VP8L), with plans to add lossy encoding. go-libwebp wraps libwebp for both lossy and lossless support, but the transpiled mode is slower, and the dynamic mode requires shared libraries. If you want simplicity and Go-native performance, nativewebp is a solid choice. For broader WebP features, go-libwebp might be better.

**Comment by HugoSmits86** [comment]
You’re always welcome to run tests, although I’d personally suggest waiting a bit since it’s very likely that most other libraries will currently produce smaller file sizes. The VP8 format is quite extensive, and until I’ve implemented all filters, options, and optimizations, other libraries will have an edge. Over the next few weeks, I plan to add these features, which should result in more comparable outputs.

**Comment by HugoSmits86** [comment]
I appreciate the idea, but I’d prefer not to include test data in the repo to avoid bloating it. Instead, please consider hosting a small dataset externally or providing a script to generate test images.
